Remove u-boot-next repo
u-boot-next repo doesn't have a firmware-panther-4920.24.B branch, so
doesn't fetch properly.

With u-boot-next in place, I get this error when I run a repo sync:
Fetching projects:  99% (153/154)
error: Exited sync due to fetch errors

- Adding newline at end of file while I'm here.

BUG=None
TEST=repo sync finishes cleanly after change.
BRANCH=firmware-panther-4920.24.B

Change-Id: Ie34989f47e002d3f9f219ee1429dfe14ba61bfc2
Signed-off-by: Martin Roth <martinroth@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/303460
Reviewed-by: Shawn N <shawnn@chromium.org>
Reviewed-by: Stefan Reinauer <reinauer@google.com>