Revert "Reland "Reland "Add back kernel-next and kernel-experimental"""
This reverts commit c7b621b18c39a50d6f3294f3bd32ce0eab81b718.

Reason for revert: Breaks branching.
See https://bugs.chromium.org/p/chromium/issues/detail?id=1017892

Original change's description:
> Reland "Reland "Add back kernel-next and kernel-experimental""
> 
> This reverts commit 7ae3ef4401585b78191fa58c514c3dee17953e02.
> 
> Reason for revert: Repo changes have been fixed.
> 
> Original change's description:
> > Revert "Reland "Add back kernel-next and kernel-experimental""
> > 
> > This reverts commit eec2ef88e732d1b5ccd2bf1950f4204a01cf1e45.
> > 
> > Reason for revert: This appears to break LCQ and PreCQLauncher at the moment.
> > 
> > https://logs.chromium.org/logs/chromeos/buildbucket/cr-buildbucket.appspot.com/8899974394474328624/+/steps/PreCQLauncher/0/stdout
> > 
> >  RunCommandError: return code: None; command: git rev-list -n1 patch_branch --
> >  [Errno 2] No such file or directory: 'src/third_party/kernel/experimental'
> > 
> > 
> > Original change's description:
> > > Reland "Add back kernel-next and kernel-experimental"
> > > 
> > > This reverts commit 5f051593e6096391c7429c57a6fd6d938f7b6ed1.
> > > 
> > > Reason for revert: repo has been fixed
> > > 
> > > Original change's description:
> > > > Revert "Add back kernel-next and kernel-experimental"
> > > > 
> > > > This reverts commit 680fb1f07172598c091dd61646de621f5630f796.
> > > > 
> > > > Reason for revert:
> > > > 
> > > > This might have caused CQ failure.
> > > > Revert this and see if that helps.
> > > > 
> > > > Exempt-From-Owner-Approval: Need to fix CQ.
> > > > BUG=chromium:1011226
> > > > TEST=none
> > > > 
> > > > Original change's description:
> > > > > Add back kernel-next and kernel-experimental
> > > > >
> > > > > These are added to the kernel-next group, so they are not synced by
> > > > > default.
> > > > >
> > > > > BUG=chromium:992138
> > > > > TEST=none
> > > > >
> > > > > Change-Id: Ic18e4ea7b86eddc5e543c278f15d171f07f9013a
> > > > > Signed-off-by: Raul E Rangel <rrangel@chromium.org>
> > > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/manifest/+/1838433
> > > > > Reviewed-by: Mike Frysinger <vapier@chromium.org>
> > > > 
> > > > Bug: chromium:992138
> > > > Change-Id: I0cffbf22be905b37e3bec3d159ec8a665e2519e9
> > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/manifest/+/1839478
> > > > Tested-by: Cheng-Yi Chiang <cychiang@chromium.org>
> > > > Reviewed-by: Cheng-Yi Chiang <cychiang@chromium.org>
> > > > Reviewed-by: Tzung-Bi Shih <tzungbi@chromium.org>
> > > > Commit-Queue: Cheng-Yi Chiang <cychiang@chromium.org>
> > > 
> > > Bug: chromium:1011226, chromium:992138
> > > Change-Id: I20e22f59f9b5b7ccd525ac4175128dbce6386466
> > > Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/manifest/+/1850656
> > > Reviewed-by: Mike Frysinger <vapier@chromium.org>
> > > Commit-Queue: Mike Frysinger <vapier@chromium.org>
> > > Tested-by: Raul E Rangel <rrangel@chromium.org>
> > > Auto-Submit: Raul E Rangel <rrangel@chromium.org>
> > 
> > Bug: chromium:1011226, chromium:992138
> > Change-Id: I3fbb32bc1cdedbfb170e019ed4943e42fca9501c
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/manifest/+/1852966
> > Reviewed-by: George Engelbrecht <engeg@google.com>
> > Reviewed-by: Sean Abraham <seanabraham@chromium.org>
> > Commit-Queue: George Engelbrecht <engeg@google.com>
> > Tested-by: George Engelbrecht <engeg@google.com>
> > Auto-Submit: George Engelbrecht <engeg@google.com>
> 
> Bug: chromium:1011226, chromium:992138
> Change-Id: I58659b116b02e833f4dca2c1d138d93e5fbad412
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/manifest/+/1871811
> Tested-by: Raul E Rangel <rrangel@chromium.org>
> Reviewed-by: Sean Abraham <seanabraham@chromium.org>
> Commit-Queue: Raul E Rangel <rrangel@chromium.org>

Bug: chromium:1011226, chromium:992138
Change-Id: I28726be42324957e02efa0772709ae1d89e285d5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/manifest/+/1879516
Reviewed-by: Bernie Thompson <bhthompson@chromium.org>
Reviewed-by: Sean Abraham <seanabraham@chromium.org>
Tested-by: Bernie Thompson <bhthompson@chromium.org>
Commit-Queue: Bernie Thompson <bhthompson@chromium.org>