cut out chrome repos
This old firmware branch doesn't care about Chrome.  Cut out the repos
because some of them don't even sync anymore:
error: revision refs/heads/master in external/WebKit_trimmed not found

BUG=None
TEST=None

Change-Id: Icfbf48b735ed04f296a5ca8ff804e59f82e71e1e
Reviewed-on: https://gerrit.chromium.org/gerrit/46745
Reviewed-by: David James <davidjames@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>