Revert "coreboot: Switch over to the chromeos-2015.07 branch"
This reverts commit 9297ac11fed4cce92710567a419012a7e8a22643.

A bunch of builders started to fail with the following error:

coreboot-0.0.1-r1095: build/vendorcode/google/chromeos/vboot2/vboot_handoff.romstage.o: In function `fill_vboot_handoff':
coreboot-0.0.1-r1095: /build/parrot/tmp/portage/sys-boot/coreboot-0.0.1-r1095/work/coreboot-0.0.1/src/vendorcode/google/chromeos/vboot2/vboot_handoff.c:62: undefined reference to `get_write_protect_state'
coreboot-0.0.1-r1095: src/arch/x86/Makefile.inc:208: recipe for target 'build/cbfs/fallback/romstage_null.debug' failed

Change-Id: I2885bdac79b567b6c5eb5f478341be02b142238d
Reviewed-on: https://chromium-review.googlesource.com/288790
Tested-by: Alex Vakulenko <avakulenko@chromium.org>
Reviewed-by: Alex Vakulenko <avakulenko@chromium.org>